# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndRelease:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      
      # Runs a set of commands using the runners shell
      - name: Restore and build
        run: |
          nuget restore OpenLibraryLabelImg.sln
          msbuild OpenLibraryLabelImg.sln -t:Build -property:Configuration=Release
      - uses: papeloto/action-zip@v1
        with:
          files: bin\Debug\net48\
          recursive: true
          dest: Release.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Release.zip"
          body: "Release compiled by git runner."
          token: ${{ secrets.GITHUB_TOKEN }}
