# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          nuget restore OpenLibraryLabelImg.sln
          msbuild OpenLibraryLabelImg.sln -t:Build

      - uses: papeloto/action-zip@v1
        with:
          files: bin\Debug\net48\ manifest.json
          recursive: true
          dest: Release.zip

      - uses: actions/upload-artifact@v2
        with:
          name: Release
          path: Release.zip
